import type { WarRoomActorConfig } from "./types";

export const WAR_ROOM_ACTORS: WarRoomActorConfig[] = [
  {
    id: "ecom-launch",
    team: "ecom-launch",
    name: "EcomLaunch",
    shortName: "指挥官",
    role: "Launch Director",
    description: "拆解目标、调度专家并汇总最终交付。",
    accent: "#f2b35f",
    glow: 0xf2b35f,
    position: { x: 47, y: 65, workX: 47, workY: 62 },
  },
  {
    id: "market-voc-researcher",
    team: "ecom-launch",
    name: "市场研究员",
    shortName: "市场",
    role: "Market & VOC Researcher",
    description: "研究竞品、市场信号与真实用户声音。",
    accent: "#e98b63",
    glow: 0xe98b63,
    position: { x: 33, y: 42, workX: 29, workY: 36 },
  },
  {
    id: "offer-architect",
    team: "ecom-launch",
    name: "方案架构师",
    shortName: "方案",
    role: "Offer Architect",
    description: "组织定位、卖点、验证假设与上市方案。",
    accent: "#d87855",
    glow: 0xd87855,
    position: { x: 21, y: 57, workX: 16, workY: 53 },
  },
  {
    id: "asset-studio",
    team: "ecom-launch",
    name: "素材工作室",
    shortName: "素材",
    role: "Asset Studio",
    description: "制作商品页、内容方向、脚本与营销资产。",
    accent: "#ca6d67",
    glow: 0xca6d67,
    position: { x: 43, y: 69, workX: 39, workY: 66 },
  },
  {
    id: "data-inspector",
    team: "data-inspector",
    name: "Growth Analyst",
    shortName: "增长",
    role: "Data & Growth Analyst",
    description: "分析上传数据、解释异常并发现可执行的经营与增长机会。",
    accent: "#78a99d",
    glow: 0x78a99d,
    position: { x: 80, y: 60, workX: 80, workY: 51 },
  },
];

export const WAR_ROOM_POLL_INTERVAL_MS = 2500;
